### ISSUE TITLE
NameError: name 'toggle_word' is not defined

### ISSUE THREAD

**Issue by joelmellon** [evandroforks/ToggleWords#2]
When installing ToggleWords (after configuring the channel properly) the plugin doesn't work. First I noticed the default key binding didn't work (Sublime just dings) then I went to the console to try the command directly. Here's my console log output starting from a fresh install:

```
ignored packages updated to: ["ToggleWords", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading python 3.3 plugin ToggleWords.ToggleWords
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
>>> toggle_word
Traceback (most recent call last):
  File "__main__", line 1, in <module>
NameError: name 'toggle_word' is not defined
>>> toggle_words
Traceback (most recent call last):
  File "__main__", line 1, in <module>
NameError: name 'toggle_words' is not defined
```

(I tried `toggle_words` in case there was a typo or something.)

Any ideas?

**Comment by evandrocoan** [comment]
To import the command, it should be `from ToggleWords import ToggleWords`, but it is a Sublime Command, I do not think you can use it directly.

I changed the default key to `"alt+w", "alt+t"` but forgot to update the readme. How did you try to use this?

**Comment by evandrocoan** [comment]
I updated readme.md and the next version should have a menu and be available on the command palette:  https://github.com/evandroforks/ToggleWords/commit/7ae962fc5a40c032e8f086632012d55cc9aeac75

**Comment by joelmellon** [comment]
OK, cool. So the "new" key binding you updated in the readme works!

Thanks for the help.

Maybe the old one was conflicting with something else on my system or in Sublime.

I assumed, I guess incorrectly, that since `toggle_word` is a "command" at least in the context of key bindings, eg. { "keys": ["alt+w", "alt+t"], "`command`": "`toggle_word`"}, that I could use it in the console to test it directly.

It's all good though, thanks very much for keeping this project alive. 🙏
